default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: admin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bipolar_sober_development

test:
  <<: *default
  database: bipolar_sober_test

production:
  <<: *default
  database: bipolar_sober_production
  username: bipolar_sober
  password: <%= ENV["PORTFOLIO_DATABASE_PASSWORD"] %>